option baron_options 'epsa =1e-3 prfreq=50 filter maxtime=3600 maxiter=-1';


solve;

# Status info
display solve_result_num, solve_result,tolerance;

# Data variables
display card(figures), coords, r;

display distances;
 
# Time stats
#display _ampl_time, _total_solve_time, _ampl_elapsed_time, _ampl_user_time;   

printf "Total time elapsed: $%6.2f.\n", _total_solve_time;
display _total_solve_time, _ampl_time, _ampl_elapsed_time, _ampl_user_time;   

quit;
